[package]
name = "google-agones-sdk"
version.workspace = true
authors.workspace = true
edition.workspace = true
publish.workspace = true

[features]
default = ["client"]
client = []
server = []

[dependencies]
futures-core.workspace = true
tonic.workspace = true
pbjson-types.workspace = true
prost.workspace = true
