# permissions for end users to view minecraftservers.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: minecraftserver-viewer-role
rules:
- apiGroups:
  - shulkermc.io
  resources:
  - minecraftservers
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - shulkermc.io
  resources:
  - minecraftservers/status
  verbs:
  - get
