apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - manifests.yaml
  - certificate.yaml

# patchesStrategicMerge:
# TODO: add when webhooks
# - webhookcainjection_patch.yaml

configurations:
  - kustomizeconfig.yaml
