apiVersion: v1
kind: Service
metadata:
  labels:
    control-plane: shulker-operator
    app.kubernetes.io/name: service
    app.kubernetes.io/instance: operator-metrics-service
    app.kubernetes.io/component: kube-rbac-proxy
    app.kubernetes.io/created-by: shulker
    app.kubernetes.io/part-of: shulker
    app.kubernetes.io/managed-by: kustomize
  name: operator-metrics-service
  namespace: system
spec:
  ports:
  - name: https
    port: 8443
    protocol: TCP
    targetPort: https
  selector:
    control-plane: shulker-operator
