name: deploy

on:
  push:
    branches:
      - main
      - rework

permissions:
  contents: read
  packages: write

env:
  TARGET_NODE_VERSION: '16'
  TARGET_JAVA_VERSION: '17'

jobs:
  publish-docker:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Use Node.js ${{ env.TARGET_NODE_VERSION }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ env.TARGET_NODE_VERSION }}

      - name: Install Node.js dependencies
        run: npm ci

      - name: Prepare Docker metadata
        id: docker-metadata
        uses: docker/metadata-action@v4
        with:
          images: ghcr.io/iamblueslime/shulker_app
          sep-tags: ";;;"
          sep-labels: ";;;"
          tags: |
            type=ref,event=branch
            type=sha,format=long
            type=sha
            type=raw,value=latest

      - name: Publish images
        uses: mansagroup/nrwl-nx-action@v3
        with:
          targets: publish-docker
          parallel: 2
          args: -- "${{ steps.docker-metadata.outputs.tags }}" "${{ steps.docker-metadata.outputs.labels }}"

  publish-maven:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Use Node.js ${{ env.TARGET_NODE_VERSION }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ env.TARGET_NODE_VERSION }}

      - name: Use Java ${{ env.TARGET_JAVA_VERSION }}
        uses: actions/setup-java@v3
        with:
          distribution: adopt
          java-version: ${{ env.TARGET_JAVA_VERSION }}
          cache: 'gradle'

      - name: Import signing GPG key
        id: gpg-signing-key
        uses: crazy-max/ghaction-import-gpg@v4
        with:
          gpg_private_key: ${{ secrets.GPG_PRIVATE_KEY }}
          passphrase: ${{ secrets.GPG_PASSPHRASE }}

      - name: Install Node.js dependencies
        run: npm ci

      - name: Publish packages
        uses: mansagroup/nrwl-nx-action@v3
        with:
          targets: publish-maven
          parallel: 3
          args: -Psigning.gnupg.keyName=${{ steps.gpg-signing-key.outputs.keyid }} -Psigning.gnupg.passphrase=${{ secrets.GPG_PASSPHRASE }}
